export http_proxy=http://16.85.88.10:8080/
export https_proxy=http://16.85.88.10:8080/


nuget restore ./Microservice/Microservice.sln -configfile ./Microservice/Microservice/nuget.config -NonInteractive
xbuild ./Microservice/Microservice.sln /t:build
sudo docker build -f ./Microservice/Microservice/Dockerfile -t hub.docker.hpecorp.net/hpefs/hpefsgatewayenterprisedirectoryservice:$BUILD_NUMBER .
